{ pkgs, treefmt-nix, ... }:
let
  # Biome owns TypeScript/JavaScript formatting; Prettier keeps everything else
  # (yaml, json, markdown, ...). The two are partitioned by extension so they
  # never fight over the same file and treefmt stays idempotent.
  jsExtensions = [
    "*.ts"
    "*.tsx"
    "*.mts"
    "*.cts"
    "*.js"
    "*.jsx"
    "*.mjs"
    "*.cjs"
  ];
  fmt = {
    projectRootFile = "flake.nix";

    settings.global.excludes = [
      "*.lock"
      "bun.lock"
      "node_modules/*"
      "dist/*"
      "coverage/*"
      # Helm chart docs are generated by helm-docs; keep treefmt out of them to
      # mirror the existing pre-commit treefmt exclude and avoid churn.
      "infra/root_chart/*"
    ];

    programs = {
      actionlint.enable = true;
      biome.enable = true;
      nixfmt.enable = true;
      prettier.enable = true;
      shfmt.enable = true;
    };

    # Biome's default include set is js + json; drop json so Prettier remains the
    # single formatter for json/jsonc (and the lockfiles stay untouched).
    settings.formatter.biome.excludes = [
      "*.json"
      "*.jsonc"
    ];

    # Mirror the non-default formatter options from biome.json so treefmt's Biome
    # (invoked with a generated --config-path) and the project's `biome` CLI /
    # pre-commit lint hook agree byte-for-byte. Only options that differ from
    # Biome's defaults need restating here.
    programs.biome.settings.formatter = {
      indentStyle = "space";
      indentWidth = 2;
      lineWidth = 100;
    };

    # Hand the js/ts extensions to Biome by excluding them from Prettier.
    settings.formatter.prettier.excludes = jsExtensions;
  };
in
(treefmt-nix.lib.evalModule pkgs fmt).config.build.wrapper
