name: ⚡ Reusable Pre-Commit
on:
  workflow_call:
jobs:
  precommit:
    name: Pre-Commit
    runs-on: ubuntu-22.04
    steps:
      - uses: AtomiCloud/actions.setup-nix@v3
        with:
          namespacelabs: false
      - name: Run pre-commit
        run: nix develop .#ci -c ./scripts/ci/pre-commit.sh
